-- ========================================
-- AI 챗봇 기반 모의투자 서비스 DDL (Oracle 19c)
-- ========================================

-- ----------------------------------------
-- 1. 사용자 / 인증
-- ----------------------------------------

CREATE TABLE users (
    user_id            NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR2(255)  NOT NULL,
    password_hash      VARCHAR2(255)  NOT NULL,
    name               VARCHAR2(100)  NOT NULL,
    phone              VARCHAR2(20),
    status             VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    email_verified_yn  CHAR(1)        DEFAULT 'N' NOT NULL,
    email_verified_at  TIMESTAMP,
    login_fail_count   NUMBER(5,0)    DEFAULT 0 NOT NULL,
    locked_at          TIMESTAMP,
    withdrawn_at       TIMESTAMP,
    service_terms_agreed_yn  CHAR(1)  DEFAULT 'N' NOT NULL,
    privacy_terms_agreed_yn  CHAR(1)  DEFAULT 'N' NOT NULL,
    marketing_agreed_yn      CHAR(1)  DEFAULT 'N' NOT NULL,
    terms_agreed_at    TIMESTAMP,
    default_market     VARCHAR2(10)   DEFAULT 'DOMESTIC',
    theme              VARCHAR2(20)   DEFAULT 'LIGHT',
    language           VARCHAR2(10)   DEFAULT 'KO',
    created_at         TIMESTAMP      NOT NULL,
    updated_at         TIMESTAMP      NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_status ON users (status);


-- ----------------------------------------
-- 2. 계좌 / 회차
-- ----------------------------------------

CREATE TABLE accounts (
    account_id         NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            NUMBER(19,0)   NOT NULL,
    account_no         VARCHAR2(30)   NOT NULL,
    account_name       VARCHAR2(100),
    account_status     VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    account_pin_hash   VARCHAR2(255)  NOT NULL,
    base_currency_code VARCHAR2(3)    DEFAULT 'KRW' NOT NULL,
    investment_tendency VARCHAR2(20),
    created_at         TIMESTAMP      NOT NULL,
    updated_at         TIMESTAMP      NOT NULL,
    CONSTRAINT uq_accounts_user_id    UNIQUE (user_id),
    CONSTRAINT uq_accounts_account_no UNIQUE (account_no),
    CONSTRAINT fk_accounts_user       FOREIGN KEY (user_id) REFERENCES users (user_id)
);


CREATE TABLE simulation_rounds (
    simulation_round_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          NUMBER(19,0)   NOT NULL,
    round_no            NUMBER(10,0)   NOT NULL,
    initial_seed_amount NUMBER(19,4)   NOT NULL,
    reset_reason_code   VARCHAR2(50),
    round_status        VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    started_at          TIMESTAMP      NOT NULL,
    ended_at            TIMESTAMP,
    created_at          TIMESTAMP      NOT NULL,
    CONSTRAINT uq_simround_account_round UNIQUE (account_id, round_no),
    CONSTRAINT fk_simround_account       FOREIGN KEY (account_id) REFERENCES accounts (account_id)
);

CREATE INDEX idx_simround_account  ON simulation_rounds (account_id);
CREATE INDEX idx_simround_status   ON simulation_rounds (round_status);


-- ----------------------------------------
-- 3. 시세 참조 마스터
-- ----------------------------------------

CREATE TABLE instruments (
    instrument_id   NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_type     VARCHAR2(20)   NOT NULL,
    instrument_type VARCHAR2(20)   NOT NULL,
    exchange_code   VARCHAR2(20),
    stock_code      VARCHAR2(20)   NOT NULL,
    stock_name      VARCHAR2(200)  NOT NULL,
    stock_name_en   VARCHAR2(200),
    sector          VARCHAR2(100),
    listing_date    DATE,
    currency_code   VARCHAR2(3)    DEFAULT 'KRW' NOT NULL,
    active_yn       CHAR(1)        DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP      NOT NULL,
    CONSTRAINT uq_instruments_market_code UNIQUE (market_type, stock_code)
);

CREATE INDEX idx_instruments_name ON instruments (stock_name);


-- ----------------------------------------
-- 4. 주문
-- ----------------------------------------

CREATE TABLE orders (
    order_id           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id         NUMBER(19,0)   NOT NULL,
    simulation_round_id NUMBER(19,0)  NOT NULL,
    instrument_id      NUMBER(19,0)   NOT NULL,
    order_no           VARCHAR2(40)   NOT NULL,
    order_channel      VARCHAR2(20)   NOT NULL,
    order_side         VARCHAR2(10)   NOT NULL,
    order_kind         VARCHAR2(20)   NOT NULL,
    order_status       VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    order_price        NUMBER(19,4),
    order_quantity     NUMBER(12,0)   NOT NULL,
    filled_quantity    NUMBER(12,0)   DEFAULT 0 NOT NULL,
    remaining_quantity NUMBER(12,0)   NOT NULL,
    reserved_amount    NUMBER(19,4),
    original_order_id  NUMBER(19,0),
    idempotency_key    VARCHAR2(100),
    requested_at       TIMESTAMP      NOT NULL,
    submitted_at       TIMESTAMP,
    cancelled_at       TIMESTAMP,
    rejected_at        TIMESTAMP,
    created_at         TIMESTAMP      NOT NULL,
    updated_at         TIMESTAMP      NOT NULL,
    CONSTRAINT uq_orders_order_no      UNIQUE (order_no),
    CONSTRAINT uq_orders_idempotency   UNIQUE (idempotency_key),
    CONSTRAINT fk_orders_account       FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_orders_simround      FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id),
    CONSTRAINT fk_orders_instrument    FOREIGN KEY (instrument_id)       REFERENCES instruments (instrument_id),
    CONSTRAINT fk_orders_original      FOREIGN KEY (original_order_id)   REFERENCES orders (order_id)
);

CREATE INDEX idx_orders_account_requested ON orders (account_id, requested_at);
CREATE INDEX idx_orders_account_status    ON orders (account_id, order_status);


-- ----------------------------------------
-- 5. 주문 이벤트
-- ----------------------------------------

CREATE TABLE order_events (
    order_event_id  NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER(19,0)   NOT NULL,
    event_type      VARCHAR2(30)   NOT NULL,
    before_status   VARCHAR2(20),
    after_status    VARCHAR2(20)   NOT NULL,
    reference_type  VARCHAR2(30),
    reference_id    VARCHAR2(100),
    event_message   VARCHAR2(1000),
    created_at      TIMESTAMP      NOT NULL,
    CONSTRAINT fk_oevents_order FOREIGN KEY (order_id) REFERENCES orders (order_id)
);

CREATE INDEX idx_oevents_order     ON order_events (order_id);
CREATE INDEX idx_oevents_created   ON order_events (created_at);


-- ----------------------------------------
-- 6. 체결
-- ----------------------------------------

CREATE TABLE executions (
    execution_id        NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            NUMBER(19,0)   NOT NULL,
    account_id          NUMBER(19,0)   NOT NULL,
    simulation_round_id NUMBER(19,0)   NOT NULL,
    instrument_id       NUMBER(19,0)   NOT NULL,
    execution_no        VARCHAR2(40)   NOT NULL,
    order_side          VARCHAR2(10)   NOT NULL,
    execution_price     NUMBER(19,4)   NOT NULL,
    execution_quantity  NUMBER(12,0)   NOT NULL,
    gross_amount        NUMBER(19,4)   NOT NULL,
    fee_amount          NUMBER(19,4)   DEFAULT 0 NOT NULL,
    tax_amount          NUMBER(19,4)   DEFAULT 0 NOT NULL,
    net_amount          NUMBER(19,4)   NOT NULL,
    executed_at         TIMESTAMP      NOT NULL,
    created_at          TIMESTAMP      NOT NULL,
    CONSTRAINT uq_executions_order      UNIQUE (order_id),
    CONSTRAINT uq_executions_no         UNIQUE (execution_no),
    CONSTRAINT fk_executions_order      FOREIGN KEY (order_id)            REFERENCES orders (order_id),
    CONSTRAINT fk_executions_account    FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_executions_simround   FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id),
    CONSTRAINT fk_executions_instrument FOREIGN KEY (instrument_id)       REFERENCES instruments (instrument_id)
);

CREATE INDEX idx_executions_account_at  ON executions (account_id, executed_at);
CREATE INDEX idx_executions_simround_at ON executions (simulation_round_id, executed_at);


-- ----------------------------------------
-- 7. 현금 원장
-- ----------------------------------------

CREATE TABLE cash_ledger (
    cash_ledger_id      NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          NUMBER(19,0)   NOT NULL,
    simulation_round_id NUMBER(19,0)   NOT NULL,
    currency_code       VARCHAR2(3)    NOT NULL,
    entry_type          VARCHAR2(30)   NOT NULL,
    amount_delta        NUMBER(19,4)   NOT NULL,
    balance_after       NUMBER(19,4)   NOT NULL,
    reference_type      VARCHAR2(30)   NOT NULL,
    reference_id        VARCHAR2(100)  NOT NULL,
    created_at          TIMESTAMP      NOT NULL,
    CONSTRAINT uq_cashledger_ref UNIQUE (reference_type, reference_id, entry_type),
    CONSTRAINT fk_cashledger_account  FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_cashledger_simround FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id)
);

CREATE INDEX idx_cashledger_acct_curr_at ON cash_ledger (account_id, currency_code, created_at);
CREATE INDEX idx_cashledger_simround_at  ON cash_ledger (simulation_round_id, created_at);


-- ----------------------------------------
-- 8. 현금 잔고
-- ----------------------------------------

CREATE TABLE cash_balances (
    cash_balance_id     NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          NUMBER(19,0)   NOT NULL,
    simulation_round_id NUMBER(19,0)   NOT NULL,
    currency_code       VARCHAR2(3)    NOT NULL,
    available_amount    NUMBER(19,4)   DEFAULT 0 NOT NULL,
    total_amount        NUMBER(19,4)   DEFAULT 0 NOT NULL,
    updated_at          TIMESTAMP      NOT NULL,
    CONSTRAINT uq_cashbal_acct_round_curr UNIQUE (account_id, simulation_round_id, currency_code),
    CONSTRAINT fk_cashbal_account  FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_cashbal_simround FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id)
);

CREATE INDEX idx_cashbal_account ON cash_balances (account_id);


-- ----------------------------------------
-- 9. 포지션 원장
-- ----------------------------------------

CREATE TABLE position_ledger (
    position_ledger_id   NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id           NUMBER(19,0)   NOT NULL,
    simulation_round_id  NUMBER(19,0)   NOT NULL,
    instrument_id        NUMBER(19,0)   NOT NULL,
    entry_type           VARCHAR2(30)   NOT NULL,
    quantity_delta        NUMBER(12,0)   NOT NULL,
    holding_quantity_after NUMBER(12,0)  NOT NULL,
    avg_buy_price_after  NUMBER(19,4),
    reference_type       VARCHAR2(30)   NOT NULL,
    reference_id         VARCHAR2(100)  NOT NULL,
    created_at           TIMESTAMP      NOT NULL,
    CONSTRAINT uq_posledger_ref UNIQUE (reference_type, reference_id, entry_type),
    CONSTRAINT fk_posledger_account    FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_posledger_simround   FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id),
    CONSTRAINT fk_posledger_instrument FOREIGN KEY (instrument_id)       REFERENCES instruments (instrument_id)
);

CREATE INDEX idx_posledger_acct_inst_at  ON position_ledger (account_id, instrument_id, created_at);
CREATE INDEX idx_posledger_simround_at   ON position_ledger (simulation_round_id, created_at);


-- ----------------------------------------
-- 10. 보유 종목
-- ----------------------------------------

CREATE TABLE holdings (
    holding_id           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id           NUMBER(19,0)   NOT NULL,
    simulation_round_id  NUMBER(19,0)   NOT NULL,
    instrument_id        NUMBER(19,0)   NOT NULL,
    holding_quantity     NUMBER(12,0)   DEFAULT 0 NOT NULL,
    avg_buy_price        NUMBER(19,4)   DEFAULT 0 NOT NULL,
    avg_buy_exchange_rate NUMBER(19,6)  DEFAULT 1 NOT NULL,
    updated_at           TIMESTAMP      NOT NULL,
    CONSTRAINT uq_holdings_acct_round_inst UNIQUE (account_id, simulation_round_id, instrument_id),
    CONSTRAINT fk_holdings_account    FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_holdings_simround   FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id),
    CONSTRAINT fk_holdings_instrument FOREIGN KEY (instrument_id)       REFERENCES instruments (instrument_id)
);

CREATE INDEX idx_holdings_account ON holdings (account_id);


-- ----------------------------------------
-- 11. 환전 주문
-- ----------------------------------------

CREATE TABLE fx_orders (
    fx_order_id         NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          NUMBER(19,0)   NOT NULL,
    simulation_round_id NUMBER(19,0)   NOT NULL,
    fx_order_no         VARCHAR2(40)   NOT NULL,
    request_channel     VARCHAR2(20)   NOT NULL,
    from_currency_code  VARCHAR2(3)    NOT NULL,
    to_currency_code    VARCHAR2(3)    NOT NULL,
    request_amount      NUMBER(19,4)   NOT NULL,
    applied_rate        NUMBER(19,6)   NOT NULL,
    fee_amount          NUMBER(19,4)   DEFAULT 0 NOT NULL,
    receive_amount      NUMBER(19,4)   NOT NULL,
    fx_order_status     VARCHAR2(20)   DEFAULT 'COMPLETED' NOT NULL,
    requested_at        TIMESTAMP      NOT NULL,
    completed_at        TIMESTAMP,
    created_at          TIMESTAMP      NOT NULL,
    CONSTRAINT uq_fxorders_no UNIQUE (fx_order_no),
    CONSTRAINT fk_fxorders_account  FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_fxorders_simround FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id)
);

CREATE INDEX idx_fxorders_account     ON fx_orders (account_id);
CREATE INDEX idx_fxorders_requested   ON fx_orders (requested_at);


-- ----------------------------------------
-- 12. 대시보드 / 위젯
-- ----------------------------------------

CREATE TABLE dashboards (
    dashboard_id    NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(19,0)   NOT NULL,
    dashboard_name  VARCHAR2(100),
    page_order      NUMBER(5,0)    NOT NULL,
    default_yn      CHAR(1)        DEFAULT 'N' NOT NULL,
    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP      NOT NULL,
    CONSTRAINT uq_dashboards_user_order UNIQUE (user_id, page_order),
    CONSTRAINT fk_dashboards_user       FOREIGN KEY (user_id) REFERENCES users (user_id)
);


CREATE TABLE widget_layouts (
    widget_layout_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashboard_id     NUMBER(19,0)   NOT NULL,
    widget_type      VARCHAR2(50)   NOT NULL,
    position_x       NUMBER(5,0)    NOT NULL,
    position_y       NUMBER(5,0)    NOT NULL,
    width            NUMBER(5,0)    NOT NULL,
    height           NUMBER(5,0)    NOT NULL,
    config_json      CLOB,
    created_at       TIMESTAMP      NOT NULL,
    updated_at       TIMESTAMP      NOT NULL,
    CONSTRAINT fk_wlayouts_dashboard FOREIGN KEY (dashboard_id) REFERENCES dashboards (dashboard_id)
);

CREATE INDEX idx_wlayouts_dashboard ON widget_layouts (dashboard_id);


-- ----------------------------------------
-- 13. 관심종목
-- ----------------------------------------

CREATE TABLE watchlist_items (
    watchlist_item_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER(19,0)   NOT NULL,
    instrument_id     NUMBER(19,0)   NOT NULL,
    display_order     NUMBER(5,0),
    created_at        TIMESTAMP      NOT NULL,
    CONSTRAINT uq_watchlist_user_inst UNIQUE (user_id, instrument_id),
    CONSTRAINT fk_watchlist_user       FOREIGN KEY (user_id)       REFERENCES users (user_id),
    CONSTRAINT fk_watchlist_instrument FOREIGN KEY (instrument_id) REFERENCES instruments (instrument_id)
);

CREATE INDEX idx_watchlist_user ON watchlist_items (user_id);


-- ----------------------------------------
-- 14. 가격 알림
-- ----------------------------------------

CREATE TABLE price_alerts (
    price_alert_id    NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER(19,0)   NOT NULL,
    instrument_id     NUMBER(19,0)   NOT NULL,
    alert_type        VARCHAR2(20)   NOT NULL,
    threshold_percent NUMBER(5,2),
    target_price      NUMBER(19,4),
    direction         VARCHAR2(10),
    active_yn         CHAR(1)        DEFAULT 'Y' NOT NULL,
    triggered_at      TIMESTAMP,
    created_at        TIMESTAMP      NOT NULL,
    CONSTRAINT fk_palerts_user       FOREIGN KEY (user_id)       REFERENCES users (user_id),
    CONSTRAINT fk_palerts_instrument FOREIGN KEY (instrument_id) REFERENCES instruments (instrument_id)
);

CREATE INDEX idx_palerts_user      ON price_alerts (user_id);
CREATE INDEX idx_palerts_user_inst ON price_alerts (user_id, instrument_id);


-- ----------------------------------------
-- 15. 알림
-- ----------------------------------------

CREATE TABLE notifications (
    notification_id   NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER(19,0)   NOT NULL,
    notification_type VARCHAR2(30)   NOT NULL,
    title             VARCHAR2(200)  NOT NULL,
    message           VARCHAR2(1000),
    reference_type    VARCHAR2(30),
    reference_id      VARCHAR2(100),
    read_yn           CHAR(1)        DEFAULT 'N' NOT NULL,
    read_at           TIMESTAMP,
    created_at        TIMESTAMP      NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_notif_user         ON notifications (user_id);
CREATE INDEX idx_notif_user_read    ON notifications (user_id, read_yn);
CREATE INDEX idx_notif_created      ON notifications (created_at);


-- ----------------------------------------
-- 16. 알림 설정
-- ----------------------------------------

CREATE TABLE notification_settings (
    notification_setting_id   NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   NUMBER(19,0)   NOT NULL,
    price_alert_enabled_yn    CHAR(1)        DEFAULT 'Y' NOT NULL,
    execution_alert_enabled_yn CHAR(1)       DEFAULT 'Y' NOT NULL,
    ai_alert_enabled_yn       CHAR(1)        DEFAULT 'Y' NOT NULL,
    default_threshold_percent  NUMBER(5,2)   DEFAULT 5.00,
    updated_at                TIMESTAMP      NOT NULL,
    CONSTRAINT uq_notifsettings_user UNIQUE (user_id),
    CONSTRAINT fk_notifsettings_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);
