-- ----------------------------------------
-- V6: 구형 수동 스키마 테이블 재생성
-- cash_balances / holdings / executions 가 V1 실행 전 수동 생성되어
-- CREATE TABLE 실패 → repair-on-migrate 통과 → 스키마 불일치 발생
-- 부분 실행 후 재시도되는 경우를 대비해 존재하는 테이블만 안전하게 삭제한다.
-- ----------------------------------------

BEGIN EXECUTE IMMEDIATE 'DROP TABLE executions CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE cash_balances CASCADE CONSTRAINTS';       EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE holdings CASCADE CONSTRAINTS';            EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE portfolio_snapshots CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;

-- ----------------------------------------
-- 6. 체결
-- ----------------------------------------

CREATE TABLE executions (
    execution_id        NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            NUMBER(19,0)   NOT NULL,
    account_id          NUMBER(19,0)   NOT NULL,
    simulation_round_id NUMBER(19,0)   NOT NULL,
    instrument_id       NUMBER(19,0)   NOT NULL,
    execution_no        VARCHAR2(40)   NOT NULL,
    order_side          VARCHAR2(10)   NOT NULL,
    execution_price     NUMBER(19,4)   NOT NULL,
    execution_quantity  NUMBER(12,0)   NOT NULL,
    gross_amount        NUMBER(19,4)   NOT NULL,
    fee_amount          NUMBER(19,4)   DEFAULT 0 NOT NULL,
    tax_amount          NUMBER(19,4)   DEFAULT 0 NOT NULL,
    net_amount          NUMBER(19,4)   NOT NULL,
    executed_at         TIMESTAMP      NOT NULL,
    created_at          TIMESTAMP      NOT NULL,
    CONSTRAINT uq_executions_order      UNIQUE (order_id),
    CONSTRAINT uq_executions_no         UNIQUE (execution_no),
    CONSTRAINT fk_executions_order      FOREIGN KEY (order_id)            REFERENCES orders (order_id),
    CONSTRAINT fk_executions_account    FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_executions_simround   FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id),
    CONSTRAINT fk_executions_instrument FOREIGN KEY (instrument_id)       REFERENCES instruments (instrument_id)
);

CREATE INDEX idx_executions_account   ON executions (account_id);
CREATE INDEX idx_executions_simround  ON executions (simulation_round_id);

-- ----------------------------------------
-- 8. 현금 잔고
-- ----------------------------------------

CREATE TABLE cash_balances (
    cash_balance_id     NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          NUMBER(19,0)   NOT NULL,
    simulation_round_id NUMBER(19,0)   NOT NULL,
    currency_code       VARCHAR2(3)    NOT NULL,
    available_amount    NUMBER(19,4)   DEFAULT 0 NOT NULL,
    total_amount        NUMBER(19,4)   DEFAULT 0 NOT NULL,
    updated_at          TIMESTAMP      NOT NULL,
    CONSTRAINT uq_cashbal_acct_round_curr UNIQUE (account_id, simulation_round_id, currency_code),
    CONSTRAINT fk_cashbal_account  FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_cashbal_simround FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id)
);

CREATE INDEX idx_cashbal_account ON cash_balances (account_id);

-- ----------------------------------------
-- 10. 보유 종목 (V5 available_quantity 포함)
-- ----------------------------------------

CREATE TABLE holdings (
    holding_id            NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id            NUMBER(19,0)   NOT NULL,
    simulation_round_id   NUMBER(19,0)   NOT NULL,
    instrument_id         NUMBER(19,0)   NOT NULL,
    holding_quantity      NUMBER(12,0)   DEFAULT 0 NOT NULL,
    available_quantity    NUMBER(12,0)   DEFAULT 0 NOT NULL,
    avg_buy_price         NUMBER(19,4)   DEFAULT 0 NOT NULL,
    avg_buy_exchange_rate NUMBER(19,6)   DEFAULT 1 NOT NULL,
    updated_at            TIMESTAMP      NOT NULL,
    CONSTRAINT uq_holdings_acct_round_inst UNIQUE (account_id, simulation_round_id, instrument_id),
    CONSTRAINT fk_holdings_account    FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_holdings_simround   FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id),
    CONSTRAINT fk_holdings_instrument FOREIGN KEY (instrument_id)       REFERENCES instruments (instrument_id)
);

CREATE INDEX idx_holdings_account ON holdings (account_id);


-- ----------------------------------------
-- 포트폴리오 스냅샷 (일별 자산 현황)
-- ----------------------------------------

CREATE TABLE portfolio_snapshots (
    snapshot_id         NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          NUMBER(19,0)   NOT NULL,
    simulation_round_id NUMBER(19,0)   NOT NULL,
    snapshot_date       DATE           NOT NULL,
    total_value         NUMBER(19,4)   NOT NULL,
    cash_krw            NUMBER(19,4)   DEFAULT 0 NOT NULL,
    cash_usd            NUMBER(19,4)   DEFAULT 0 NOT NULL,
    usd_exchange_rate   NUMBER(19,6)   DEFAULT 1 NOT NULL,
    stock_value         NUMBER(19,4)   DEFAULT 0 NOT NULL,
    daily_return        NUMBER(10,4),
    created_at          TIMESTAMP      NOT NULL,
    CONSTRAINT uq_psnap_acct_round_date UNIQUE (account_id, simulation_round_id, snapshot_date),
    CONSTRAINT fk_psnap_account  FOREIGN KEY (account_id)          REFERENCES accounts (account_id),
    CONSTRAINT fk_psnap_simround FOREIGN KEY (simulation_round_id) REFERENCES simulation_rounds (simulation_round_id)
);

CREATE INDEX idx_psnap_account_date ON portfolio_snapshots (account_id, snapshot_date);
