-- ----------------------------------------
-- 16. 국내 차트 캔들
-- ----------------------------------------

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'MARKET_DAILY_CANDLES';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE market_daily_candles (
                daily_candle_id  NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                instrument_id    NUMBER(19,0)   NOT NULL,
                exchange_scope   CHAR(1)        DEFAULT 'U' NOT NULL,
                trade_date       DATE           NOT NULL,
                open_price       NUMBER(19,4)   NOT NULL,
                high_price       NUMBER(19,4)   NOT NULL,
                low_price        NUMBER(19,4)   NOT NULL,
                close_price      NUMBER(19,4)   NOT NULL,
                volume           NUMBER(19,0)   DEFAULT 0 NOT NULL,
                trading_value    NUMBER(19,0),
                source_tr_cd     VARCHAR2(10)   NOT NULL,
                created_at       TIMESTAMP      NOT NULL,
                updated_at       TIMESTAMP      NOT NULL,
                CONSTRAINT uq_mkt_daily_candles UNIQUE (instrument_id, exchange_scope, trade_date),
                CONSTRAINT ck_mkt_daily_scope CHECK (exchange_scope IN ('K', 'N', 'U')),
                CONSTRAINT fk_mkt_daily_instrument FOREIGN KEY (instrument_id) REFERENCES instruments (instrument_id)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'MARKET_MINUTE_CANDLES';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE market_minute_candles (
                minute_candle_id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                instrument_id    NUMBER(19,0)   NOT NULL,
                exchange_scope   CHAR(1)        DEFAULT 'U' NOT NULL,
                interval_minute  NUMBER(4,0)    NOT NULL,
                candle_at        TIMESTAMP      NOT NULL,
                open_price       NUMBER(19,4)   NOT NULL,
                high_price       NUMBER(19,4)   NOT NULL,
                low_price        NUMBER(19,4)   NOT NULL,
                close_price      NUMBER(19,4)   NOT NULL,
                volume           NUMBER(19,0)   DEFAULT 0 NOT NULL,
                trading_value    NUMBER(19,0),
                adjustment_code  NUMBER(13,0),
                adjustment_rate  NUMBER(10,4),
                price_sign       CHAR(1),
                source_tr_cd     VARCHAR2(10)   NOT NULL,
                created_at       TIMESTAMP      NOT NULL,
                updated_at       TIMESTAMP      NOT NULL,
                CONSTRAINT uq_mkt_minute_candles UNIQUE (instrument_id, exchange_scope, interval_minute, candle_at),
                CONSTRAINT ck_mkt_minute_scope CHECK (exchange_scope IN ('K', 'N', 'U')),
                CONSTRAINT ck_mkt_minute_interval CHECK (interval_minute > 0),
                CONSTRAINT fk_mkt_minute_instrument FOREIGN KEY (instrument_id) REFERENCES instruments (instrument_id)
            )
        ]';
    END IF;
END;
/
